- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: add variable to playbook
      include_var: vpc_setup
        
    - name: create vpc
      ec2_vpc_net:
        name: "{{vpc_name}}"
        region: "{{region}}"
        cidr_block: "{{vpcCidr}}"
        dns_support: yes
        dns_hostnames: yes
        tenancy: default
        state: "{{state}}"
      register: vpcout
    
    - name: create public subnet1
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        az: "{{zone1}}"
        map_public: yes
        region: "{{region}}"
        cidr: "{{pubSubCidr1}}"
        state: "{{state}}"
        tags:
          Name: vpro_pub1
      register: vpro_pub1

  